const metaData = {
  home: {
    title: "Magic Club Marketplace",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  privacy: {
    title: "Privacy Policy",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  terms: {
    title: "Terms & Conditions",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  faq: {
    title: "FAQs",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  contact: {
    title: "Contact Us",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  explore: {
    title: "Explore",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  auction: {
    title: "Auction",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  collections: {
    title: "Collection",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  create_asset: {
    title: "Create Asset",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  sign_in: {
    title: "Sign In",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  sign_up: {
    title: "Sign Up",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  verify_email: {
    title: "Verify Email",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  reset_password: {
    title: "Reset Password",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  my_bids: {
    title: "My Bids",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  my_profile: {
    title: "My Profile",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  profile_settings: {
    title: "Profile Settings",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  edit_profile: {
    title: "Edit Profile",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  change_password: {
    title: "Change Password",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  change_email: {
    title: "Change Email",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  theme: {
    title: "Theme",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  language: {
    title: "Language",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  trending_sellers: {
    title: "Trending Sellers",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  trending_creators: {
    title: "Trending Creators",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
  bookmarks: {
    title: "Bookmarks",
    description: "Web site created using create-react-app",
    type: "website",
    logo: `/logo192.png`,
    URL: `/`,
  },
};

export default metaData;
